public class StatisticsDataPointDto {
    public string id;
    public string sku;
    public string name;
    public boolean isMapped;
    public boolean isIgnored;
    public string storefrontId;
    public string brandId;
    public integer price;
    public integer quantity;
    public integer quantityOnHand;
    public integer quantityOnDemand;
    public integer quantityInTransit;
    public integer quantityAvailable;
    public integer soldPerWeekAvg;
    public integer inventoryStatus;
    
} 