public class WarehouseDto {
    @AuraEnabled
    public String id;
    
    @AuraEnabled
    public String name;
    
    @AuraEnabled
    public String code;
    
    @AuraEnabled
    public String addressBusinessName;
    
    @AuraEnabled
    public String addressLine1;
    
    @AuraEnabled
    public String addressLine2;
    
    @AuraEnabled
    public String addressZipCode;
    
    @AuraEnabled
    public String addressCity;
    
    @AuraEnabled
    public String addressState;
    
    @AuraEnabled
    public String addressCountryCode;
    
    @AuraEnabled
    public DateTime createDateTimeUtc;
    
    @AuraEnabled
    public DateTime modifyDateTimeUtc;
} 